# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/configuration/#theme-parameters

colorScheme = "noir"
defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = false
disableImageOptimization = true

enableSearch = false
enableCodeCopy = true

mainSections = ["work"]
# robots = ""

[header]
  layout = "fixed" # valid options: basic, fixed

[footer]
 # showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = false
  showScrollToTop = true

[homepage]  
  layout = "page" # valid options: page, profile, hero, card, background, custom
  homepageImage = "img/cover.png" # used in: hero, and card
  showRecent = true
  showRecentItems = 4
  showMoreLink = false
  showMoreLinkDest = "/work"
  cardView = false
  cardViewScreenWidth = true
  layoutBackgroundBlur = true # only used when layout equals background
  disableImageZoom = true

[article]
  showDate = false
  #showViews = true
  #showLikes = true
  showDateUpdated = false
  showAuthor = false
  showHero = true
  heroStyle = "big" # valid options: basic, big, background
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  # editURL = "https://github.com/username/repo/"
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = false
  showPagination = true
  invertPagination = false
  showReadingTime = false
  showTableOfContents = false
  showTaxonomies = false 
  showAuthorsBadges = false 
  showWordCount = false
  showSummary = true
  # sharingLinks = [ "linkedin", "twitter", "whatsapp", "pinterest", "reddit", "facebook", "email"]

[list]
  layoutBackgroundHeaderSpace = false
  showBreadcrumbs = false
  showSummary = true
  showTableOfContents = false
  showCards = true
  groupByYear = false
  cardView = false
  cardViewScreenWidth = false

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = true

[firebase]
  # apiKey = "XXXXXX"
  # authDomain = "XXXXXX"
  # projectId = "XXXXXX"
  # storageBucket = "XXXXXX"
  # messagingSenderId = "XXXXXX"
  # appId = "XXXXXX"
  # measurementId = "XXXXXX"

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
